package ua.petproject.entity;

import ua.petproject.annotations.*;

@Entity
@Table(name = "archive")
public class Archive {
    @Id
    @AutoGeneratedValue
    @Column(name = "id")
    private Long id;

    @Column(name = "report_id")
    @OneToAny(tableName = "report")
    private Report report;

    public Archive(Long id, Report report) {
        this.id = id;
        this.report = report;
    }

    public Archive(Report report) {
        this.report = report;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "Archive{" +
                "id=" + id +
                ", report=" + report +
                '}';
    }

    public Report getReport() {
        return report;
    }

    public void setReport(Report report) {
        this.report = report;
    }
}
