package ua.petproject.entity;

import ua.petproject.annotations.*;
import javax.persistence.Id;

/**
 * Class for testing tables creation.
 */
@Entity
@Table(name = "customer_unique_table_name")
public class Customer {

    @Id
    @AutoGeneratedValue
    @Column(name = "id")
    public Long id;

    @Column(name = "name", max = 100)
    private String name;

    @Column(name = "email")
    private String email;

    @Column(name = "age")
    private int age;


    public Customer(){}

    public Customer(String name, String email, int age) {
        this.name = name;
        this.email = email;
        this.age = age;
    }

    public Customer(Long id, String name, String email, int age) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", age=" + age +
                '}';
    }
}
